import Head from "next/head";
import { Inter } from "next/font/google";
import { BASE_URL, API_KEY,BASE_PATH } from "../../lib/constant";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import Layout from "../../components/layout";
function Home({ movies }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="row">
            {movies.results.map((movie) => (
              <div className="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 col-xxl-2 ">
                        <Link href={{
                          pathname: `/movies/${movie.id}`,
                          query: {
                            movie: JSON.stringify(movie)
                          }
                        }} 
                        as={`/movies/${movie.id}`}
                        className="text-decoration-none">
                        <div className="card border-0 shadow-sm h-100">
                            <img src={BASE_PATH + movie.backdrop_path} className="card-img-top" alt="..." />
                            <div className="card-body">
                                <p className="card-text">{movie.title}</p>
                            </div>
                        </div>
                        </Link>
                      </div>
            ))}
          </div>
        </div>
      </main>
    </Layout>
  );
}
export async function getServerSideProps() {
  console.log(`${BASE_URL}/movie/popular?api_key=${API_KEY}&page=1`);
  const resp = await fetch(
    `${BASE_URL}movie/popular?api_key=${API_KEY}&page=1`
  );
  const results = await resp.json();
  // console.log(results)
  return {
    props: {
      movies: results,
    },
  };
}
export default Home;
